/**
 * Autumn Serenity theme definition.
 *
 * Every colour comes from `palette.js`; nothing here should be a raw hex value.
 * Keys follow the VS Code theme reference:
 * https://code.visualstudio.com/api/references/theme-color
 */

import { palette as p, alpha } from './palette.js';

const workbench = {
  // Base
  'foreground': p.cream,
  'descriptionForeground': alpha(p.cream, 'b0'),
  'disabledForeground': alpha(p.cream, '70'),
  'icon.foreground': p.cream,
  'focusBorder': p.parchment,
  'progressBar.background': p.pumpkin,
  'sash.hoverBorder': p.pumpkin,
  'window.activeBorder': p.soil,
  'window.inactiveBorder': p.soil,

  // Text & links
  'textLink.foreground': p.pumpkin,
  'textLink.activeForeground': p.pumpkinLight,
  'editorLink.activeForeground': p.pumpkin,

  // Badges & buttons
  'badge.background': p.brick,
  'badge.foreground': p.cream,
  'button.background': p.walnut,
  'button.foreground': p.parchment,
  'button.hoverBackground': p.moss,
  'button.secondaryBackground': p.walnut,
  'button.secondaryForeground': p.parchment,
  'button.secondaryHoverBackground': p.moss,
  'checkbox.background': p.cocoa,
  'checkbox.border': p.driftwood,
  'checkbox.foreground': p.pumpkin,
  'toolbar.hoverBackground': p.walnut,

  // Inputs & dropdowns
  'input.background': p.soil,
  'input.foreground': p.parchment,
  'input.border': p.driftwood,
  'input.placeholderForeground': p.clay,
  'inputOption.activeBackground': p.moss,
  'inputOption.activeForeground': p.parchment,
  'inputOption.activeBorder': p.sand,
  'inputValidation.infoBorder': p.amber,
  'inputValidation.warningBorder': p.flame,
  'inputValidation.errorBorder': p.ember,
  'dropdown.background': p.cocoa,
  'dropdown.foreground': p.parchment,

  // Editor
  'editor.background': p.soil,
  'editor.foreground': p.parchment,
  'editorCursor.foreground': p.pumpkin,
  'editor.lineHighlightBackground': alpha(p.driftwood, '70'),
  'editor.lineHighlightBorder': p.driftwood,
  'editor.selectionBackground': p.walnut,
  'editor.selectionHighlightBackground': alpha(p.walnut, '70'),
  'editor.inactiveSelectionBackground': alpha(p.amber, '70'),
  'editor.wordHighlightBackground': alpha(p.flame, '50'),
  'editor.wordHighlightStrongBackground': alpha(p.ember, '70'),
  'editor.findMatchBackground': p.amber,
  'editor.findMatchHighlightBackground': alpha(p.amber, '70'),
  'editor.findRangeHighlightBackground': alpha(p.soil, '70'),
  'editor.rangeHighlightBackground': alpha(p.soil, '70'),
  'editor.hoverHighlightBackground': p.transparent,
  'editorLineNumber.foreground': p.clay,
  'editorLineNumber.activeForeground': p.parchment,
  'editorWhitespace.foreground': p.driftwood,
  'editorRuler.foreground': p.amber,
  'editorIndentGuide.background1': p.rust,
  'editorBracketHighlight.foreground1': p.amber,
  'editorBracketHighlight.foreground2': p.fern,
  'editorBracketHighlight.foreground3': p.pumpkin,
  'editorBracketHighlight.foreground4': p.lichen,
  'editorBracketHighlight.foreground5': p.marigold,
  'editorBracketHighlight.foreground6': p.tangerine,
  'editorBracketHighlight.unexpectedBracket.foreground': p.ember,
  'editorBracketPairGuide.activeBackground1': alpha(p.amber, '80'),
  'editorBracketPairGuide.activeBackground2': alpha(p.fern, '80'),
  'editorBracketPairGuide.activeBackground3': alpha(p.pumpkin, '80'),
  'editorBracketPairGuide.activeBackground4': alpha(p.lichen, '80'),
  'editorBracketPairGuide.activeBackground5': alpha(p.marigold, '80'),
  'editorBracketPairGuide.activeBackground6': alpha(p.tangerine, '80'),
  'editorBracketMatch.background': p.driftwood,
  'editorBracketMatch.border': p.driftwood,
  'editorCodeLens.foreground': p.parchment,
  'editorInlayHint.typeBackground': p.rust,
  'editorInlayHint.typeForeground': p.parchment,

  // Diagnostics
  'editorError.foreground': p.ember,
  'editorWarning.foreground': p.flame,
  'editorInfo.foreground': p.amber,
  'editorHint.foreground': p.amber,

  // Gutter & overview ruler
  'editorGutter.background': p.soil,
  'editorGutter.addedBackground': p.amber,
  'editorGutter.modifiedBackground': p.rust,
  'editorGutter.deletedBackground': p.ember,
  'editorOverviewRuler.findMatchForeground': alpha(p.pumpkin, 'a0'),
  'minimap.findMatchHighlight': p.pumpkin,

  // Editor widgets (suggest, hover, find, peek)
  'editorWidget.background': p.soil,
  'editorWidget.foreground': p.cream,
  'editorWidget.border': p.driftwood,
  'editorWidget.resizeBorder': p.pumpkin,
  'editorHoverWidget.background': p.soil,
  'editorHoverWidget.foreground': p.cream,
  'editorSuggestWidget.background': p.soil,
  'editorSuggestWidget.border': p.driftwood,
  'editorSuggestWidget.foreground': p.parchment,
  'editorSuggestWidget.highlightForeground': p.clay,
  'editorSuggestWidget.selectedBackground': p.rust,
  'peekView.border': p.driftwood,
  'peekViewEditor.background': p.soil,
  'peekViewEditor.matchHighlightBackground': p.clay,
  'peekViewResult.background': p.driftwood,
  'peekViewResult.fileForeground': p.parchment,
  'peekViewResult.lineForeground': p.clay,
  'peekViewResult.matchHighlightBackground': p.clay,
  'peekViewResult.selectionBackground': alpha(p.driftwood, '6b'),
  'peekViewResult.selectionForeground': p.amber,
  'peekViewTitle.background': p.rust,
  'peekViewTitleDescription.foreground': p.clay,
  'peekViewTitleLabel.foreground': p.parchment,

  // Editor groups & tabs
  'editorGroup.border': p.seam,
  'editorGroupHeader.tabsBackground': p.soil,
  'tab.border': p.seam,
  'tab.activeBackground': p.moss,
  'tab.activeForeground': p.parchment,
  'tab.activeBorderTop': p.pumpkin,
  'tab.inactiveBackground': p.soil,
  'tab.inactiveForeground': p.clay,
  'tab.hoverBackground': p.moss,
  'tab.hoverForeground': p.parchment,
  'tab.unfocusedHoverBackground': p.soil,
  'tab.unfocusedHoverForeground': p.parchment,
  'tab.activeModifiedBorder': p.amber,
  'tab.inactiveModifiedBorder': p.driftwood,
  'tab.unfocusedActiveModifiedBorder': p.amber,
  'tab.unfocusedInactiveModifiedBorder': p.driftwood,
  'breadcrumb.foreground': alpha(p.cream, 'b0'),
  'breadcrumb.focusForeground': p.cream,
  'breadcrumb.activeSelectionForeground': p.cream,

  // Merge conflicts
  'merge.border': p.seam,
  'merge.currentHeaderBackground': alpha(p.amber, '70'),
  'merge.currentContentBackground': alpha(p.amber, '70'),
  'merge.incomingHeaderBackground': alpha(p.amber, '70'),
  'merge.incomingContentBackground': alpha(p.amber, '70'),
  'merge.commonHeaderBackground': alpha(p.rust, '70'),
  'merge.commonContentBackground': alpha(p.rust, '70'),

  // Scrollbar
  'scrollbar.shadow': p.rust,
  'scrollbarSlider.background': p.driftwood,
  'scrollbarSlider.hoverBackground': p.rust,
  'scrollbarSlider.activeBackground': p.flame,

  // Activity bar & sidebar
  'activityBar.background': p.soil,
  'activityBar.foreground': p.pumpkin,
  'activityBar.inactiveForeground': p.wheat,
  'activityBar.activeBorder': p.pumpkin,
  'activityBarBadge.background': p.brick,
  'activityBarBadge.foreground': p.cream,
  'sideBar.background': p.soil,
  'sideBar.foreground': p.straw,
  'sideBar.border': p.seam,
  'sideBarTitle.foreground': p.cream,
  'sideBarSectionHeader.foreground': p.cream,

  // Lists & trees
  'list.activeSelectionBackground': p.moss,
  'list.activeSelectionForeground': p.parchment,
  'list.inactiveSelectionBackground': p.cocoa,
  'list.inactiveSelectionForeground': p.parchment,
  'list.hoverBackground': p.walnut,
  'list.hoverForeground': p.parchment,
  'list.focusBackground': p.clay,
  'list.focusForeground': p.parchment,
  'list.focusOutline': p.transparent,
  'list.highlightForeground': p.pumpkin,
  'list.focusHighlightForeground': p.pumpkin,
  'list.filterMatchBackground': alpha(p.pumpkin, '40'),
  'list.filterMatchBorder': p.pumpkin,

  // Command palette / quick input
  'quickInput.foreground': p.cream,
  'quickInputTitle.background': p.cocoa,
  'pickerGroup.foreground': p.pumpkin,
  'pickerGroup.border': p.seam,
  'keybindingLabel.foreground': p.cream,

  // Menus
  'menu.background': p.cocoa,
  'menu.foreground': p.cream,
  'menu.selectionForeground': p.cream,
  'menubar.selectionForeground': p.cream,

  // Panel & terminal
  'panel.background': p.soil,
  'panel.border': p.seam,
  'panelTitle.activeBorder': p.pumpkin,
  'panelTitle.activeForeground': p.parchment,
  'panelTitle.inactiveForeground': p.clay,
  'terminal.background': p.soil,
  'terminal.foreground': p.cream,
  'terminal.border': p.seam,
  'terminal.selectionBackground': p.walnut,
  'terminal.findMatchBackground': p.amber,
  'terminal.findMatchHighlightBackground': alpha(p.amber, '70'),
  'terminalCursor.foreground': p.pumpkin,
  'terminalCursor.background': p.soil,
  'terminal.ansiBlack': p.bark,
  'terminal.ansiRed': p.ember,
  'terminal.ansiGreen': p.fern,
  'terminal.ansiYellow': p.marigold,
  'terminal.ansiBlue': p.pumpkin,
  'terminal.ansiMagenta': p.rust,
  'terminal.ansiCyan': p.lichen,
  'terminal.ansiWhite': p.parchment,
  'terminal.ansiBrightBlack': p.clay,
  'terminal.ansiBrightRed': p.flame,
  'terminal.ansiBrightGreen': p.fern,
  'terminal.ansiBrightYellow': p.straw,
  'terminal.ansiBrightBlue': p.pumpkinLight,
  'terminal.ansiBrightMagenta': p.tangerine,
  'terminal.ansiBrightCyan': p.lichen,
  'terminal.ansiBrightWhite': p.cream,

  // Status bar & title bar
  'statusBar.background': p.soil,
  'statusBar.foreground': p.parchment,
  'statusBar.border': p.seam,
  'statusBar.debuggingBackground': p.ember,
  'statusBar.debuggingForeground': p.parchment,
  'statusBar.noFolderBackground': p.clay,
  'statusBar.noFolderForeground': p.amber,
  'statusBarItem.remoteBackground': p.brick,
  'statusBarItem.remoteForeground': p.cream,
  'titleBar.activeBackground': p.soil,
  'titleBar.activeForeground': p.parchment,
  'titleBar.inactiveBackground': p.bark,
  'titleBar.inactiveForeground': p.clay,
  'titleBar.border': p.seam,

  // Notifications
  'notifications.background': p.walnut,
  'notifications.foreground': p.cream,
  'notificationCenterHeader.background': p.soil,
  'notificationCenterHeader.foreground': p.parchment,
  'notificationToast.border': p.driftwood,
  'notificationsErrorIcon.foreground': p.ember,
  'notificationsWarningIcon.foreground': p.flame,
  'notificationsInfoIcon.foreground': p.amber,

  // Debug
  'debugToolBar.background': p.soil,
  'debugToolBar.border': p.seam,
  'debugConsole.errorForeground': p.ember,
  'debugConsole.warningForeground': p.flame,
  'debugConsole.infoForeground': p.parchment,
  'debugExceptionWidget.background': p.soil,
  'debugExceptionWidget.border': p.driftwood,

  // Git, extensions, settings, welcome
  'gitDecoration.modifiedResourceForeground': p.amber,
  'gitDecoration.addedResourceForeground': p.fern,
  'gitDecoration.untrackedResourceForeground': p.fern,
  'gitDecoration.deletedResourceForeground': p.ember,
  'gitDecoration.conflictingResourceForeground': p.flame,
  'gitDecoration.stageModifiedResourceForeground': p.amber,
  'gitDecoration.stageDeletedResourceForeground': p.ember,
  'gitDecoration.ignoredResourceForeground': p.clay,
  'gitDecoration.submoduleResourceForeground': p.wheat,
  'extensionButton.prominentBackground': p.pumpkin,
  'extensionButton.prominentForeground': p.bark,
  'extensionButton.prominentHoverBackground': p.pumpkinLight,
  'extensionBadge.remoteBackground': p.brick,
  'extensionBadge.remoteForeground': p.cream,
  'settings.headerForeground': p.cream,
  'settings.modifiedItemIndicator': p.pumpkin,
  'welcomePage.progress.foreground': p.pumpkin,
  'welcomePage.progress.background': p.walnut,
  'welcomePage.tileBorder': p.seam,
  'walkThrough.embeddedEditorBackground': p.soil,
};

const tokenColors = [
  { name: 'Comments', scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: p.mocha, fontStyle: 'italic' } },
  { name: 'Keywords & storage', scope: ['keyword', 'storage.type', 'storage.modifier', 'variable.language'], settings: { foreground: p.pumpkin } },
  { name: 'Operators', scope: ['keyword.operator'], settings: { foreground: p.wheat } },
  { name: 'Variables', scope: ['variable', 'variable.other', 'meta.definition.variable'], settings: { foreground: p.tangerine } },
  { name: 'Parameters & properties', scope: ['variable.parameter', 'variable.other.property', 'variable.other.object.property', 'meta.object.key', 'meta.object-literal.key', 'support.type.property-name'], settings: { foreground: p.parchment } },
  { name: 'Strings', scope: ['string'], settings: { foreground: p.amber } },
  { name: 'Template expressions & escapes', scope: ['punctuation.definition.template-expression', 'constant.character.escape', 'string.regexp'], settings: { foreground: p.flame } },
  { name: 'Constants & numbers', scope: ['constant', 'constant.numeric', 'constant.language', 'constant.other'], settings: { foreground: p.flame } },
  { name: 'Functions', scope: ['entity.name.function', 'support.function', 'meta.function-call', 'entity.name.method'], settings: { foreground: p.fern } },
  { name: 'Types & classes', scope: ['entity.name.type', 'entity.name.class', 'entity.name.interface', 'entity.name.namespace', 'entity.other.inherited-class', 'support.type', 'support.class'], settings: { foreground: p.lichen } },
  { name: 'Decorators & annotations', scope: ['meta.decorator', 'punctuation.decorator', 'storage.type.annotation'], settings: { foreground: p.marigold } },
  { name: 'Support & built-ins', scope: ['support', 'support.variable', 'support.constant'], settings: { foreground: p.pumpkin } },
  { name: 'Tags', scope: ['entity.name.tag', 'punctuation.definition.tag'], settings: { foreground: p.rust } },
  { name: 'Tag attributes', scope: ['entity.other.attribute-name'], settings: { foreground: p.marigold, fontStyle: 'italic' } },
  { name: 'Punctuation', scope: ['punctuation', 'meta.brace'], settings: { foreground: p.sand } },
  { name: 'CSS selectors', scope: ['entity.name.tag.css', 'entity.other.attribute-name.class.css', 'entity.other.attribute-name.id.css', 'entity.other.attribute-name.pseudo-class.css'], settings: { foreground: p.fern, fontStyle: '' } },
  { name: 'CSS properties', scope: ['support.type.property-name.css', 'support.type.property-name.scss'], settings: { foreground: p.parchment } },
  { name: 'CSS values & units', scope: ['support.constant.property-value.css', 'keyword.other.unit', 'constant.numeric.css'], settings: { foreground: p.flame } },
  { name: 'JSON keys', scope: ['support.type.property-name.json', 'meta.structure.dictionary.key'], settings: { foreground: p.lichen } },
  { name: 'Markdown headings', scope: ['markup.heading', 'entity.name.section', 'punctuation.definition.heading.markdown'], settings: { foreground: p.amber, fontStyle: 'bold' } },
  { name: 'Markdown bold', scope: ['markup.bold'], settings: { foreground: p.tangerine, fontStyle: 'bold' } },
  { name: 'Markdown italic', scope: ['markup.italic'], settings: { foreground: p.tangerine, fontStyle: 'italic' } },
  { name: 'Markdown links', scope: ['markup.underline.link', 'markup.underline.link.markdown', 'string.other.link'], settings: { foreground: p.pumpkin } },
  { name: 'Markdown code', scope: ['markup.inline.raw', 'markup.fenced_code.block', 'markup.raw.block'], settings: { foreground: p.fern } },
  { name: 'Markdown quotes & lists', scope: ['markup.quote', 'punctuation.definition.list.begin.markdown'], settings: { foreground: p.mocha } },
  { name: 'Diff inserted', scope: ['markup.inserted'], settings: { foreground: p.fern } },
  { name: 'Diff deleted', scope: ['markup.deleted'], settings: { foreground: p.ember } },
  { name: 'Invalid', scope: ['invalid', 'invalid.illegal'], settings: { foreground: p.ember } },
];

/** Semantic tokens (from language servers) — keep them aligned with the TextMate rules above. */
const semanticTokenColors = {
  'function': p.fern,
  'method': p.fern,
  'type': p.lichen,
  'class': p.lichen,
  'interface': p.lichen,
  'enum': p.lichen,
  'struct': p.lichen,
  'typeParameter': p.lichen,
  'namespace': p.lichen,
  'keyword': p.pumpkin,
  'variable': p.tangerine,
  'parameter': p.parchment,
  'property': p.parchment,
  'decorator': p.marigold,
  'operator': p.wheat,
  'string': p.amber,
  'number': p.flame,
  'comment': p.mocha,
};

export const theme = {
  $schema: 'vscode://schemas/color-theme',
  name: 'Autumn Serenity',
  type: 'dark',
  semanticHighlighting: true,
  colors: workbench,
  tokenColors,
  semanticTokenColors,
};
